name: ci qemu

on:
  push:

jobs:
  qemu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_build_sha: ['29c05d13']
        build_arch: [arm64, ppc64le, s390x]
        build_type: ['Release', 'Debug']
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: 💎 Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      -
        name: 🔧 Prepare
        id: prep
        run: |
          # Set output parameters.
          export DOCKER_TAG="reivilo1234/cxx-cmake:${{ matrix.docker_build_sha }}-${{ matrix.build_arch }}"
          echo ::set-output name=tags::${DOCKER_TAG}
      -
        name: 🔧 Configure Endn
        run: |
          cmake -E make_directory build
          docker run --rm -v $(pwd):/src/ ${{ steps.prep.outputs.tags }} \
            cmake \
            -DENDN_ENABLE_TESTS=ON \
            -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" \
            -B /src/build/ -S /src
      -
        name: 🔨 Build Tests
        run: |
          docker run --rm -v $(pwd):/src/ ${{ steps.prep.outputs.tags }} \
            cmake --build /src/build --target "EndnTests" --config "${{ matrix.build_type }}" -j
      -
        name: ✅ Run Tests
        run: |
          docker run --rm -v $(pwd):/src/ ${{ steps.prep.outputs.tags }} \
            /bin/bash -c "cd /src/build && ctest --build-config "${{ matrix.build_type }}" --progress --verbose"
